
/*
 * DO NOT EDIT THIS FILE.
 *
 * This file is machine generated and any changes are likely to be overwritten
 * by future updates.
 */

package org.lappsgrid.discriminator;

public class Discriminators
{
    protected Discriminators() { }

    public static class Values
    {

       public static final long ERROR = 0;
       public static final long OK = 1;
       public static final long META = 2;
       public static final long TEXT = 3;
       public static final long XML = 4;
       public static final long STRING_LIST = 5;
       public static final long DEPRECATED = 6;
       public static final long SYSTEM = 128;
       public static final long LOGIN = 129;
       public static final long AUTHORIZATION = 130;
       public static final long ONE_PER_LINE = 512;
       public static final long TSV = 513;
       public static final long CSV = 514;
       public static final long SPACE_SEPARATED = 515;
       public static final long DOCUMENT = 1024;
       public static final long GATE = 1025;
       public static final long UIMA = 1026;
       public static final long STANFORD = 1027;
       public static final long OPENNLP = 1028;
       public static final long GRAF = 1029;
       public static final long PTB = 1030;
       public static final long JSON = 1031;
       public static final long JSON_LD = 1032;
       public static final long LAPPS = 1034;
       public static final long ANNOTATION = 2048;
       public static final long CHUNK = 2049;
       public static final long PARAGRAPH = 2050;
       public static final long SENTENCE = 2051;
       public static final long TOKEN = 2052;
       public static final long POS = 2053;
       public static final long COREF = 2054;
       public static final long NE = 2055;
       public static final long PERSON = 2056;
       public static final long LOCATION = 2057;
       public static final long DATE = 2058;
       public static final long ORGANIZATION = 2059;
       public static final long NCHUNK = 2060;
       public static final long VCHUNK = 2061;
       public static final long LEMMA = 2062;
       public static final long LOOKUP = 2063;
       public static final long MATCHES = 2064;
       public static final long QUERY = 3072;
       public static final long GET = 3073;
       public static final long INDEX = 3074;
       public static final long LIST = 3075;
       public static final long LUCENE = 3076;
       public static final long SQL = 3077;
       public static final long SPARQL = 3078;
       public static final long REGEX = 3079;
       public static final long COMPOSITE = 3080;
       public static final long SIZE = 3081;
       public static final long GETMETADATA = 3082;
       public static final long EXECUTE = 3083;
       public static final long SOLR = 3084;
       public static final long SCHEMA = 3085;
       public static final long LICENSE = 524287;
       public static final long PUBLIC_DOMAIN = 524288;
       public static final long OPEN_SOURCE = 524289;
       public static final long APACHE2 = 524290;
       public static final long GPL = 524291;
       public static final long LGPL = 524292;
       public static final long BSD = 524293;
       public static final long ECLIPSE = 524294;
       public static final long NO_COMMERCIAL = 524295;
       public static final long RESTRICTED = 524296;
       public static final long GPL2 = 524297;
       public static final long GPL3 = 524298;
       public static final long LGPL21 = 524299;
       public static final long LGPL3 = 524300;
       public static final long BSD2 = 524301;
       public static final long BSD3 = 524302;
       public static final long MIT = 524303;
       public static final long CC = 524304;
       public static final long CC0 = 524305;
       public static final long CC_BY = 524306;
       public static final long CC_BY_SA = 524307;
       public static final long CC_BY_ND = 524308;
       public static final long CC_BY_NC = 524309;
       public static final long CC_BY_NC_SA = 524310;
       public static final long CC_BY_NC_ND = 524311;
       public static final long USAGE = 525311;
       public static final long RESEARCH = 525312;
       public static final long COMMERCIAL = 525313;
       public static final long EDUCATION = 525314;
       public static final long NON_PROFIT = 525315;
       public static final long PERSONAL = 525316;
       public static final long ANY = 525317;

    }

    public static class Uri
    {

       public static final String ERROR = "http://vocab.lappsgrid.org/ns/error"; 
       public static final String OK = "http://vocab.lappsgrid.org/ns/ok"; 
       public static final String META = "http://vocab.lappsgrid.org/ns/meta"; 
       public static final String TEXT = "http://vocab.lappsgrid.org/ns/media/text"; 
       public static final String XML = "http://vocab.lappsgrid.org/ns/media/xml"; 
       public static final String STRING_LIST = "http://vocab.lappsgrid.org/ns/string-list"; 
       public static final String DEPRECATED = "http://vocab.lappsgrid.org/ns/deprecated"; 
       public static final String SYSTEM = "http://vocab.lappsgrid.org/ns/system"; 
       public static final String LOGIN = "http://vocab.lappsgrid.org/ns/system#login"; 
       public static final String AUTHORIZATION = "http://vocab.lappsgrid.org/ns/system#authorization"; 
       public static final String ONE_PER_LINE = "http://vocab.lappsgrid.org/ns/media/text#newline-separated"; 
       public static final String TSV = "http://vocab.lappsgrid.org/ns/media/text#tab-separated"; 
       public static final String CSV = "http://vocab.lappsgrid.org/ns/media/text#comma-separated"; 
       public static final String SPACE_SEPARATED = "http://vocab.lappsgrid.org/ns/media/text#space-separated"; 
       public static final String DOCUMENT = "http://vocab.lappsgrid.org/Document"; 
       public static final String GATE = "http://vocab.lappsgrid.org/ns/media/xml#gate"; 
       public static final String UIMA = "http://vocab.lappsgrid.org/ns/media/xml#uima-cas"; 
       public static final String STANFORD = "http://vocab.lappsgrid.org/ns/media/text#stanford"; 
       public static final String OPENNLP = "http://vocab.lappsgrid.org/ns/media/text#opennlp"; 
       public static final String GRAF = "http://vocab.lappsgrid.org/ns/media/xml#graf-standoff"; 
       public static final String PTB = "http://vocab.lappsgrid.org/ns/media/text#ptb"; 
       public static final String JSON = "http://vocab.lappsgrid.org/ns/media/json"; 
       public static final String JSON_LD = "http://vocab.lappsgrid.org/ns/media/jsonld"; 
       public static final String LAPPS = "http://vocab.lappsgrid.org/ns/media/jsonld#lif"; 
       public static final String ANNOTATION = "http://vocab.lappsgrid.org/Annotation"; 
       public static final String CHUNK = "http://vocab.lappsgrid.org/Chunk"; 
       public static final String PARAGRAPH = "http://vocab.lappsgrid.org/Paragraph"; 
       public static final String SENTENCE = "http://vocab.lappsgrid.org/Sentence"; 
       public static final String TOKEN = "http://vocab.lappsgrid.org/Token"; 
       public static final String POS = "http://vocab.lappsgrid.org/Token#pos"; 
       public static final String COREF = "http://vocab.lappsgrid.org/Coreference"; 
       public static final String NE = "http://vocab.lappsgrid.org/NamedEntity"; 
       public static final String PERSON = "http://vocab.lappsgrid.org/Person"; 
       public static final String LOCATION = "http://vocab.lappsgrid.org/Location"; 
       public static final String DATE = "http://vocab.lappsgrid.org/Date"; 
       public static final String ORGANIZATION = "http://vocab.lappsgrid.org/Organization"; 
       public static final String NCHUNK = "http://vocab.lappsgrid.org/NounChunk"; 
       public static final String VCHUNK = "http://vocab.lappsgrid.org/VerbChunk"; 
       public static final String LEMMA = "http://vocab.lappsgrid.org/Token#lemma"; 
       public static final String LOOKUP = "http://vocab.lappsgrid.org/Lookup"; 
       public static final String MATCHES = "http://vocab.lappsgrid.org/NamedEntity#matches"; 
       public static final String QUERY = "http://vocab.lappsgrid.org/ns/action/query"; 
       public static final String GET = "http://vocab.lappsgrid.org/ns/action/get"; 
       public static final String INDEX = "http://vocab.lappsgrid.org/ns/action/index"; 
       public static final String LIST = "http://vocab.lappsgrid.org/ns/action/list"; 
       public static final String LUCENE = "http://vocab.lappsgrid.org/ns/action/query#lucene"; 
       public static final String SQL = "http://vocab.lappsgrid.org/ns/action/query#sql"; 
       public static final String SPARQL = "http://vocab.lappsgrid.org/ns/action/query#sparql"; 
       public static final String REGEX = "http://vocab.lappsgrid.org/ns/action/query#regex"; 
       public static final String COMPOSITE = "http://vocab.lappsgrid.org/ns/action/query#composite"; 
       public static final String SIZE = "http://vocab.lappsgrid.org/ns/action/size"; 
       public static final String GETMETADATA = "http://vocab.lappsgrid.org/ns/action/get-metadata"; 
       public static final String EXECUTE = "http://vocab.lappsgrid.org/ns/action/execute"; 
       public static final String SOLR = "http://vocab.lappsgrid.org/ns/action/query#solr"; 
       public static final String SCHEMA = "http://vocab.lappsgrid.org/ns/action/query#solr-schema"; 
       public static final String LICENSE = "http://vocab.lappsgrid.org/ns/license"; 
       public static final String PUBLIC_DOMAIN = "http://vocab.lappsgrid.org/ns/license#public-domain"; 
       public static final String OPEN_SOURCE = "http://vocab.lappsgrid.org/ns/license#open-source"; 
       public static final String APACHE2 = "http://vocab.lappsgrid.org/ns/license#apache-2.0"; 
       public static final String GPL = "http://vocab.lappsgrid.org/ns/license#gpl"; 
       public static final String LGPL = "http://vocab.lappsgrid.org/ns/license#lgpl"; 
       public static final String BSD = "http://vocab.lappsgrid.org/ns/license#bsd"; 
       public static final String ECLIPSE = "http://vocab.lappsgrid.org/ns/license#eclipse"; 
       public static final String NO_COMMERCIAL = "http://vocab.lappsgrid.org/ns/license#non-commercial"; 
       public static final String RESTRICTED = "http://vocab.lappsgrid.org/ns/license#restricted"; 
       public static final String GPL2 = "http://vocab.lappsgrid.org/ns/license#gpl-2.0"; 
       public static final String GPL3 = "http://vocab.lappsgrid.org/ns/license#gpl-3.0"; 
       public static final String LGPL21 = "http://vocab.lappsgrid.org/ns/license#lgpl-2.1"; 
       public static final String LGPL3 = "http://vocab.lappsgrid.org/ns/license#lgpl-3.0"; 
       public static final String BSD2 = "http://vocab.lappsgrid.org/ns/license#bsd-2-clause"; 
       public static final String BSD3 = "http://vocab.lappsgrid.org/ns/license#bsd-3-clause"; 
       public static final String MIT = "http://vocab.lappsgrid.org/ns/license#mit"; 
       public static final String CC = "http://vocab.lappsgrid.org/ns/license#cc"; 
       public static final String CC0 = "http://vocab.lappsgrid.org/ns/license#cc0"; 
       public static final String CC_BY = "http://vocab.lappsgrid.org/ns/license#cc-by"; 
       public static final String CC_BY_SA = "http://vocab.lappsgrid.org/ns/license#cc-by-sa"; 
       public static final String CC_BY_ND = "http://vocab.lappsgrid.org/ns/license#cc-by-nd"; 
       public static final String CC_BY_NC = "http://vocab.lappsgrid.org/ns/license#cc-by-nc"; 
       public static final String CC_BY_NC_SA = "http://vocab.lappsgrid.org/ns/license#cc-by-nc-sa"; 
       public static final String CC_BY_NC_ND = "http://vocab.lappsgrid.org/ns/license#cc-by-nc-nd"; 
       public static final String USAGE = "http://vocab.lappsgrid.org/ns/allow"; 
       public static final String RESEARCH = "http://vocab.lappsgrid.org/ns/allow#research"; 
       public static final String COMMERCIAL = "http://vocab.lappsgrid.org/ns/allow#commercial"; 
       public static final String EDUCATION = "http://vocab.lappsgrid.org/ns/allow#education"; 
       public static final String NON_PROFIT = "http://vocab.lappsgrid.org/ns/allow#non-profit"; 
       public static final String PERSONAL = "http://vocab.lappsgrid.org/ns/allow#personal"; 
       public static final String ANY = "http://vocab.lappsgrid.org/ns/allow#any"; 

    }
}

